backend/controllers/MailController.php
<?php
    namespace backend\controllers;

    use fluid\Mail;
    use Yii;
    use yii\base\ErrorException;

    class MailController extends BaseController{

        public function beforeAction($action){
            $this->redirect(['site/index']);
        }

        public function actionIndex(){
            $this->view->title = "Poczta";

            try{
                $mail = new Mail("imap.gmail.com", 993, "imap/ssl", "mrowa94@gmail.com", "Julita96");
                $mail->listMailboxes();
            }
            catch(ErrorException $ex){
                Yii::$app->session->setFlash('error', 'dsa');
            }

            return $this->render("index");
        }
    }

backend/controllers/UserController.php
<?php
    namespace backend\controllers;

    use backend\models\UserCreate;
    use backend\models\UserUpdate;
    use Yii;
    use common\models\User;
    use backend\models\UserSearch;
    use yii\filters\AccessControl;
    use yii\helpers\ArrayHelper;
    use yii\web\NotFoundHttpException;
    use yii\filters\VerbFilter;
    use yii\web\Response;
    use yii\widgets\ActiveForm;

    class UserController extends BaseController{
        public function behaviors(){
            return [
                'verbs' => [
                    'class' => AccessControl::className(),
                    'rules' => [
                        [
                            'actions' => ['view'],
                            'allow' => true,
                            'roles' => ["editor"]
                        ],
                        [
                            'allow' => true,
                            'roles' => ['admin'],
                        ],
                    ],
                ],
            ];
        }

        public function actionIndex(){
            $this->view->title = "Użytkownicy";
            $this->view->params['breadcrumbs'][] = $this->view->title;
            $searchModel = new UserSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }
        public function actionView($id){
            $model = $this->findModel($id);

            $this->view->title = "Profil użytkownika";
            $this->view->params['breadcrumbs'][] = ['label' => "Użytkownicy", 'url' => ['index']];
            $this->view->params['breadcrumbs'][] = $this->view->title;

            return $this->render('view', [
                'model' => $model,
            ]);
        }
        public function actionCreate(){
            $model = new UserCreate();

            $roles = Yii::$app->authManager->getRoles();
            $roles = ArrayHelper::map($roles, 'name', 'description');
            $avatars = User::getAvatars();
            $sex = ['men' => 'Mężyczyzna', 'women' => 'Kobieta'];

            $this->view->title = 'Utwórz użytkownika';
            $this->view->params['breadcrumbs'][] = ['label' => 'Użytkownicy', 'url' => ['index']];
            $this->view->params['breadcrumbs'][] = $this->view->title;

            if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;

                return ActiveForm::validate($model);
            }

            if ($model->load(Yii::$app->request->post()) && $model->create()) {
                return $this->redirect(['view', 'id' => $model->user->id]);
            }
            else {
                return $this->render('create', [
                    'model' => $model,
                    'roles' => $roles,
                    'sex' => $sex,
                    'avatars' => $avatars,
                ]);
            }
        }
        public function actionUpdate($id){
            $model = new UserUpdate($id);

            $roles = Yii::$app->authManager->getRoles();
            $roles = ArrayHelper::map($roles, 'name', 'description');
            $avatars = User::getAvatars();
            $sex = ['men' => 'Mężyczyzna', 'women' => 'Kobieta'];

            $this->view->title ='Edycja użytkownika';
            $this->view->params['breadcrumbs'][] = ['label' => "Użytkownicy", 'url' => ['index']];
            $this->view->params['breadcrumbs'][] = $this->view->title;

            if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;

                return ActiveForm::validate($model);
            }

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
            else {
                return $this->render('update', [
                    'model' => $model,
                    'roles' => $roles,
                    'sex' => $sex,
                    'avatars' => $avatars,
                ]);
            }
        }
        public function actionDelete($id){
            $this->findModel($id)->delete();

            return $this->redirect(['index']);
        }
        protected function findModel($id){
            if (($model = User::findOne($id)) !== null) {
                return $model;
            }
            else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
        }
    }

backend/views/partials/footer.php
<footer class="main-footer">
    <strong>Copyright &copy; 2016 <a href="http://pawel-mrowiec.pl">Paweł Mrowiec</a>.</strong>
    <span class="hidden-xs">Wszystkie prawa zastrzeżone.</span>
</footer>

backend/views/partials/header.php
<?php
    use yii\helpers\Url;

    $user = Yii::$app->user->identity;
?>

<header class="main-header">
    <a href="<?= Url::home(); ?>" class="logo hidden-xs">
        <span class="logo-mini">
            <i class="fa fa-dashboard"></i>
        </span>
    </a>

    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle hidden-lg hidden-md" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= $user->avatar; ?>" class="user-image" alt="User Image">
                        <span class="hidden-xs">
                            <?= $user->username;?>
                        </span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="<?= $user->avatar; ?>" class="img-circle" alt="User Image">
                            <p>
                                <?= $user->username; ?>
                                <small>Dołączył <?= $user->created_at; ?></small>
                            </p>
                        </li>

                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="<?= Url::toRoute(["user/view", 'id' => Yii::$app->user->identity->id]); ?>" class="btn btn-default btn-flat">Profil</a>
                            </div>
                            <div class="pull-right">
                                <a href="<?= Url::toRoute("/logout"); ?>" class="btn btn-default btn-flat">Wyloguj</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <?php /*<li>
                    <a href="<?= Url::toRoute(["mail/index"]); ?>">
                        <i class="fa fa-envelope"></i>
                    </a>
                </li>*/ ?>
                <li>
                    <a href="<?= Yii::getAlias("@frontendLink"); ?>">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
            </ul>
        </div>

    </nav>
</header>

backend/views/partials/sidebar.php
<?php
    use yii\helpers\Url;
    $user = Yii::$app->user->identity;
?>
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <a href="<?= Url::toRoute(["user/view", 'id' => Yii::$app->user->identity->id]); ?>">
                    <img src="<?= $user->avatar;?>" class="img-circle" alt="User Image">
                </a>
            </div>
            <div class="pull-left info">
                    <p>
                        <a href="<?= Url::toRoute(["user/view", 'id' => Yii::$app->user->identity->id]); ?>">
                            <?= $user->username;?>
                        </a>
                    </p>
                    <a href="mailto:<?= $user->email;?>">
                        <i class="fa fa-envelope text-success"></i>
                        <?= $user->email; ?>
                    </a>
            </div>
        </div>

        <ul class="sidebar-menu">
            <li class="header">Nawigacja</li>
            <?php if(!empty($this->params['groups'])): ?>
                <?php foreach($this->params['groups']  AS $group): ?>
                    <li class="treeview">
                        <a href="<?= $group->url; ?>">
                            <i class="<?= $group->icon; ?>"></i>
                            <span><?= $group->name; ?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php /*
            <li class="active treeview">
                <ul class="treeview-menu">
                    <li><a href="index.html"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                    <li class="active"><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-files-o"></i>
                    <span>Layout Options</span>
                    <span class="label label-primary pull-right">4</span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/layout/top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
                    <li><a href="pages/layout/boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
                    <li><a href="pages/layout/fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
                    <li><a href="pages/layout/collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
                </ul>
            </li>
            <li>
                <a href="pages/widgets.html">
                    <i class="fa fa-th"></i> <span>Widgets</span> <small class="label pull-right bg-green">new</small>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Charts</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a></li>
                    <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
                    <li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
                    <li><a href="pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-laptop"></i>
                    <span>UI Elements</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
                    <li><a href="pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
                    <li><a href="pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
                    <li><a href="pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
                    <li><a href="pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
                    <li><a href="pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Forms</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
                    <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                    <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Tables</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
                    <li><a href="pages/tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
                </ul>
            </li>
            <li>
                <a href="pages/calendar.html">
                    <i class="fa fa-calendar"></i> <span>Calendar</span>
                    <small class="label pull-right bg-red">3</small>
                </a>
            </li>
            <li>
                <a href="pages/mailbox/mailbox.html">
                    <i class="fa fa-envelope"></i> <span>Mailbox</span>
                    <small class="label pull-right bg-yellow">12</small>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Examples</span>
                    <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
                    <li><a href="pages/examples/profile.html"><i class="fa fa-circle-o"></i> Profile</a></li>
                    <li><a href="pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
                    <li><a href="pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
                    <li><a href="pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
                    <li><a href="pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
                    <li><a href="pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
                    <li><a href="pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
                </ul>
            </li>

            <li><a href="documentation/index.html"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
            <li class="header">LABELS</li>
            <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
            */ ?>
        </ul>
    </section>
</aside>